name: deploy
on: [push, pull_request]
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Package dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material
          pip install mkdocs-glightbox
      - name: Deploy
        run: mkdocs gh-deploy --force